version: '3.8'

services:
  # Servicio de Base de Datos (PostgreSQL + PostGIS)
  db:
    image: postgis/postgis:15-3.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bomberos_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecreto
    ports:
      - "5432:5432"

  # Servicio Web (Django)
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=bomberos_db
      - DB_USER=postgres
      - DB_PASSWORD=supersecreto
      - DB_HOST=db

volumes:
  postgres_data: